[package]
name = "bdf2surface"
version = "0.0.1"
authors = ["Locez"]
edition = "2021"
description = "A crate to convert bdf font to sdl2 surface"
license = "MIT"


[dependencies]  
bdf = "0.6.0"
sdl2 = "0.37.0"
